#!/bin/bash
# Railway Deployment Script - Ethara AI (Nexus Pro)
# This script helps you update environment variables on Railway

echo "🚀 Railway Deployment Helper"
echo "============================"
echo ""
echo "CODE STATUS:"
echo "✅ All code changes have been committed and pushed to GitHub"
echo "✅ Git Commit: feat: Re-enable Google OAuth with real Client ID and update Auth pages"
echo "✅ Repository: https://github.com/Siddhanth2509/Nexus-Pro-Web-App"
echo ""

echo "📋 NEXT STEPS - Update Environment Variables on Railway:"
echo ""
echo "For BACKEND Service:"
echo "-------------------"
echo "1. Go to: https://railway.app/dashboard"
echo "2. Select your 'Nexus Pro' project"
echo "3. Click on the 'backend' service"
echo "4. Click on 'Variables' tab in the top menu"
echo "5. Add/Update these variables:"
echo ""
echo "   GOOGLE_CLIENT_ID = 303017670558-78ih5a84btn61pjsni2oluss41lgac7g.apps.googleusercontent.com"
echo "   NODE_ENV = production"
echo ""
echo "6. Click 'Deploy' or save to trigger redeploy"
echo ""

echo "For FRONTEND Service:"
echo "-------------------"
echo "1. In the same Railway dashboard, click on the 'frontend' service"
echo "2. Click on 'Variables' tab in the top menu"
echo "3. Add/Update these variables:"
echo ""
echo "   VITE_GOOGLE_CLIENT_ID = 303017670558-78ih5a84btn61pjsni2oluss41lgac7g.apps.googleusercontent.com"
echo "   VITE_API_URL = https://<your-backend-domain>.railway.app"
echo ""
echo "   (Replace <your-backend-domain> with your actual backend domain from Railway)"
echo ""
echo "4. Click 'Deploy' or save to trigger redeploy"
echo ""

echo "🔍 VERIFICATION STEPS:"
echo "--------------------"
echo "After both services redeploy (2-3 minutes):"
echo ""
echo "1. Visit your frontend: https://<your-frontend-domain>.railway.app"
echo "2. Check that the 'Sign in with Google' button is visible"
echo "3. Test login with:"
echo "   Email: admin@ethara.ai"
echo "   Password: Admin@123"
echo "4. Verify dashboard loads with all data"
echo ""

echo "✨ DEPLOYMENT COMPLETE!"
echo ""
echo "For detailed instructions, see: RAILWAY_DEPLOYMENT_GUIDE.md"
